### ISSUE TITLE
--disable-curses still attempts to use ncurses (undefined references)

### ISSUE THREAD

**Issue by ionenwks** [quakeforge/quakeforge#15]
With ./configure --disable-curses --disable-Werror:
```
/tmp/quakeforge/ruamoko/qwaq/builtins/curses.c:1447: undefined reference to `COLORS'
/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: ruamoko/qwaq/builtins/curses.o: in function `bi_max_color_pairs':
/tmp/quakeforge/ruamoko/qwaq/builtins/curses.c:1453: undefined reference to `COLOR_PAIRS'
/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: ruamoko/qwaq/builtins/curses.o: in function `bi_qwaq_clear':
/tmp/quakeforge/ruamoko/qwaq/builtins/curses.c:1926: undefined reference to `endwin'
/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: ruamoko/qwaq/builtins/curses.o: in function `bi_initialize':
```

**Edit:** along with --disable-png, I know these options are not very interesting to disable -- I'm attempting to package a snapshot given 0.7.2 doesn't work so well anymore with newer toolchain and having better results with current, and going through what I can and can't offer as an option

**Comment by taniwha** [comment]
Thank you. Reproduced.

**Comment by taniwha** [comment]
I'm sill thinking about just how I want to go about fixing this. The problem is that qwaq-curses is used to run vkgen, and disabling curses for a program named "...-curses" seems a tad odd. It comes down to what direction I want to take qwaq as a tool.

**Comment by ionenwks** [comment]
Well, if it's clear that it's required with --enable-vulkan, e.g. configure requests it rather than a build failure, as far as I'm concern I don't see a problem, unless you feel supporting lack of curses is worth it.

**Comment by taniwha** [comment]
I'm beginning to wonder, actually, but it turns out this is a bit harder than I expected. I've been poking at it and qwaq's `main.c` (which I want to use in general) is rather tied to the concept of "main (debugger) app" + "secondary (target) app", but fortunately, this seems to be in one spot. qwaq-curses started out with being a quakec debugger as its goal (but with eventual future expansion in mind). I *think* it's just the `thread->progsinit` setup loop that need work (maybe some more primary options?). Also, the debugger really needs to be able to have control over thread creation etc.

Of course, another option is a dead-simple QC runner since threading isn't needed for vkgen.
